name: Test workflow

# Controls when the workflow will run
# Runs on push to main
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install de-client
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install de-client --extra-index-url=https://$DASH_ENTERPRISE_HOST/packages
        env:
          DASH_ENTERPRISE_HOST: ${{secrets.DASH_ENTERPRISE_HOST}}
      - name: Inject code and deploy
        shell: bash
        if: github.event.action != 'closed'
        run: |
          DASH_ENTERPRISE_USERNAME=$DASH_ENTERPRISE_USERNAME DASH_ENTERPRISE_PASSWORD=$DASH_ENTERPRISE_PASSWORD de --host $DASH_ENTERPRISE_HOST --no-keyfile login
          de whoami
          DASH_ENTERPRISE_USERNAME=$DASH_ENTERPRISE_USERNAME DASH_ENTERPRISE_PASSWORD=$DASH_ENTERPRISE_PASSWORD de --host $DASH_ENTERPRISE_HOST --no-keyfile deploy ${{ github.workspace }} --name $APP_NAME --message "Deploying app" -y
        env:
          DASH_ENTERPRISE_HOST: ${{secrets.DASH_ENTERPRISE_HOST}}
          DASH_ENTERPRISE_PASSWORD: ${{secrets.DASH_ENTERPRISE_PASSWORD}}
          DASH_ENTERPRISE_USERNAME: ${{secrets.DASH_ENTERPRISE_USERNAME}}
          APP_NAME: ${{secrets.APP_NAME}}
          
